export const jobsTemplates = [
  {
    id: "1",
    templateTitle: "Deep dive",
    templateDescription: null,
    title: "Deep dive",
    slug: "deep-dive",
    description:
      "<h2>About the Job</h2><p><em>Write ~2 paragraphs explaining the job. The first paragraph should include relevant context and background about your project. The second paragraph should explain the goals of the job itself (e.g. areas to explore, features to discuss, context around the purpose of the job, etc). Please make sure to write the job in the 3rd person (i.e. avoid &ldquo;we&rdquo;). For examples, see this page: https://superteam.fun/jobs</em></p><p>&nbsp;</p><p>&nbsp;</p><h2>Evaluation Criteria</h2><p><em>Job hunters will use the bullet points below to understand how they&rsquo;ll be evaluated. Feel free to add more criteria (e.g. if you want them to discuss a specific feature of your project), or edit the bullet points below as needed.</em></p><p>&nbsp;</p><h3>Depth</h3><ul><li>Did you explore the background of the project?</li><li>Does your essay talk about the key features of the project?</li><li>Is your essay the one-stop-resource for people to get up to speed with this project?</li><li>Did you learn everything there is to know about the project?</li><li>Did you take screenshots, provide a step by step guide to onboarding, and clearly articulate the value the project offers?</li><li>Did you join the project&rsquo;s Discord and get a feel for the community?</li><li>Did you try the competition and explain relative pros/cons of this project?</li></ul><p>&nbsp;</p><h3><strong>Writing Style</strong></h3><ul><li>Did you write a compelling introduction and a satisfying conclusion?</li><li>Is your writing easy and fun to read?</li><li>Did you avoid overly complex jargon?</li><li>Did you explain concepts in a way a person new to crypto could understand?</li></ul><p>&nbsp;</p><h3><strong>Submission Requirements</strong></h3><ul><li>Did you write your essay in English?</li><li>Is your submission at least 1,000 words? Note that typical job winners are ~2,000 words.</li><li>Did you include links to your sources under the title &ldquo;References&rdquo;? If you have used external sources and no references are included, your job could be rejected on grounds of plagiarism.</li></ul><p>&nbsp;</p><h2>Resources</h2><p><em>Please add any links to your project, socials, or any reference essays that may help the job hunters write a great deep dive. Consider including your Medium/Substack, Twitter, Discord, docs, website, and anything else that might prove helpful.</em></p><ul><li>Deep Dive Guidelines: https://superteamdao.notion.site/Deep-Dive-Job-Guidelines-bb86ec5ac3a14087b018b90afe69d5bd</li></ul><p>&nbsp;</p><h2>Terms</h2><p>Participation in this job is entirely voluntary. Jobs are a way to learn and dabble in opportunities to build in web3. These are neither full time jobs nor project based engagement. Please be advised that the companies will not have time for individualized feedback due to the number of entries we receive.</p>",
    requirements: null,
    deadline: null,
    eligibility: null,
    token: null,
    rewardAmount: null,
    rewards: null,
    color: "#FDF8F0",
    emoji: "✍️",
    isFeatured: false,
    isActive: true,
    isArchived: false,
    createdAt: "2023-06-08T10:09:56.130Z",
    updatedAt: "2023-06-08T10:09:56.130Z",
    skills: [{ skills: "Content", subskills: ["Writing"] }],
    type: "open",
    Jobs: [],
  },
  {
    id: "2",
    templateTitle: "UI/UX Review",
    templateDescription: null,
    title: "UI/UX Review",
    slug: "ui-ux-review",
    description:
      '<h2>About the Job</h2><p>Write ~2 paragraphs explaining the job. The first paragraph should include relevant context and background about your project. The second paragraph should explain the goals of the job itself (e.g. areas to explore, features to redesign, context around the purpose of the job, etc). Please make sure to write the job in the 3rd person (i.e. avoid &ldquo;we&rdquo;). For examples, see this <a href="https://superteam.fun/500-jobs" target="_blank">page</a>.</p><p>&nbsp;</p><h2>Rewards</h2><p><strong>🥇 First Prize:</strong></p><ul><li>Replace with 1st prize (we recommend at least $3,000 USDC or equivalent of your token)</li></ul><p>&nbsp;</p><p><strong>🥈 Second Prize</strong></p><ul><li>Replace with 2nd prize (we recommend at least $500 USDC or equivalent of your token)</li></ul><p>&nbsp;</p><p><strong>🥉 Third Prize</strong></p><ul><li>Replace with 3rd prize (we recommend at least $250 USDC or equivalent of your token, but this is optional)</li></ul><h2>&nbsp;</h2><h2>Evaluation Criteria</h2><p><em>Job hunters will use the bullet points below to understand how they&rsquo;ll be evaluated. Feel free to add more criteria or edit the bullet points below as needed.</em></p><p>&nbsp;</p><h3><strong>Depth</strong></h3><ul><li>Did you identify problems for each screen you examined?</li><li>Did you explain what the user goals are for the different areas of the product you\'re reviewing?</li><li>Did you include screenshots of the existing designs?</li><li>Did you create a new design that solves the problems you identified?</li><li>Did you redesign the marketing website as well as any application or interior pages? In other words, did you redesign everything that is publicly visible?</li><li>Did you package your review into a nice presentation (e.g. Notion, Google Slides, Figma, etc)?</li></ul><p>&nbsp;</p><h3><strong>Submission requirement</strong></h3><ul><li>Share your submission on Twitter &amp; tag @<em>yourproject</em></li><li>Check out <a href="https://superteam.substack.com/" target="_blank">previous job winners</a> to get a sense of the quality we expect.</li></ul><h2>&nbsp;</h2><h2>Resources</h2><p><em>Please add any links to your project, socials, or anything else that will give Job Hunters a sense of what kind of design you&rsquo;re looking for. Consider including your Medium/Substack, Twitter, Discord, docs, website, and anything else that might prove helpful.</em></p><p>&nbsp;</p><h2>Terms</h2><p><em>Participation in this job is entirely voluntary. Jobs are a way to learn and dabble in opportunities to build in web3. These are neither full time jobs nor project based engagement. Please be advised that the companies will not have time for individualized feedback due to the number of entries we receive.</em></p>',
    requirements: null,
    deadline: null,
    eligibility: null,
    token: null,
    rewardAmount: null,
    rewards: null,
    color: "#F4F0FD",
    emoji: "🖼️",
    isFeatured: false,
    isActive: true,
    isArchived: false,
    createdAt: "2023-06-08T10:09:56.129Z",
    updatedAt: "2023-06-08T10:09:56.129Z",
    skills: [{ skills: "Design", subskills: ["UI/UX Design"] }],
    type: "open",
    Jobs: [],
  },
  {
    id: "3",
    templateTitle: "Create a dashboard",
    templateDescription: null,
    title: "Create a dashboard",
    slug: "create-a-dashboard",
    description:
      "<h2>About the Job</h2><p><em>Below this box, please write 1-2 paragraphs explaining your project. This might include a description of your mission, a demonstration of your traction, your investors, or anything else that gets job hunters excited about working together.</em></p><h2>&nbsp;</h2><h2>Metrics to Include</h2><p><em>The section should explain what a success dashboard would include. Below are a few suggested metrics to include, but feel free to remove/reduce as needed. </em></p><p>&nbsp;</p><p><strong>General Dashboards</strong></p><ul><li>Identify 24hr volume</li><li>Get the number of trades in last 24 hrs</li><li>Cumulative Volume</li><li>Cumulative Trades</li><li>Cumulative Unique Wallets</li><li>Total Value Staked</li><li>Number of nodes</li><li>TVL</li><li>Treasury Value</li></ul><p>&nbsp;</p><p><strong>NFT-Specific Dashboards</strong></p><ul><li>List of contracts that have minted the most tokens</li><li>Floor price</li><li>Average daily sales volume</li></ul><p>&nbsp;</p><p><strong>General Token Dashboard</strong></p><ul><li>Total Supply</li><li>Circulating Supply</li><li>Number of token holders over time</li><li>Market cap</li><li>Fully Diluted Value</li></ul><h2>&nbsp;</h2><h2>Resources</h2><p><em>Please add any links to your project, socials, or any reference dashboards that may help the job hunters understand your project. Consider including your Medium/Substack, Twitter, Discord, docs, website, and anything else that might prove helpful.</em></p><h2>&nbsp;</h2><h2>Terms</h2><p>Participation in this job is entirely voluntary. Jobs are a way to learn and dabble in opportunities to build in web3. These are neither full time jobs nor project based engagement. Please be advised that the companies will not have time for individualized feedback due to the number of entries we receive</p>",
    requirements: null,
    deadline: null,
    eligibility: null,
    token: null,
    rewardAmount: null,
    rewards: null,
    color: "#F0FCFD",
    emoji: "📈",
    isFeatured: false,
    isActive: true,
    isArchived: false,
    createdAt: "2023-06-08T10:09:56.130Z",
    updatedAt: "2023-06-08T10:09:56.130Z",
    skills: [{ skills: "Other", subskills: ["Data Analytics"] }],
    type: "open",
    Jobs: [],
  },
  {
    id: "4",
    templateTitle: "Product feedback",
    templateDescription: null,
    title: "Product feedback",
    slug: "product-feedback",
    description:
      '<h2>About the Job</h2><p><em>Write ~2 paragraphs explaining the job. The first paragraph should include relevant context and background about your project. The second paragraph should explain the goals of the job itself (e.g. areas to explore, features to discuss, context around the purpose of the job, etc). Please make sure to write the job in the 3rd person (i.e. avoid &ldquo;we&rdquo;). For examples, see this page: https://superteam.fun/jobs</em></p><p>&nbsp;</p><p><strong>Job Task: </strong>Sign up for an account with &ldquo;YOUR PROJECT NAME&rdquo; and write a feedback report on your experience and general product recommendations that come to mind. Use the evaluation criteria and set of questions below to write your report.</p><p>&nbsp;</p><h2><strong>Evaluation Criteria</strong></h2><ol><li>Did you use the <a href="https://docs.google.com/document/d/1Qaxi5ybbn3J6iaqDM02G-94X0NSV4NJD09UmeU_IU_I/edit?mode=html" target="_blank">Feedback Template</a>? (<em>Feel free to copy the Template &amp; add your own custom questions. Kindly limit the number of questions to 6-10 Max). </em></li><li>Did you provide both positive and negative feedback in your report?</li><li>Did you discuss various features of the product and your experience using it?</li><li>Did you include screenshots describing the issues or highlights for positive commentary?</li><li>Did you limit your responses to 70-100 words per question?</li></ol><p>&nbsp;</p><p>&nbsp;</p><h2>Resources</h2><p><em>Add any links to your project, socials, or any reference essays that may help the job hunters write a great product review. Consider including your Medium/Substack, Twitter, Discord, docs, website, access to your product ( early access links, app files, etc) and anything else that might prove helpful.</em></p><h2>&nbsp;</h2><h2>Terms</h2><p>Participation in this job is entirely voluntary. Jobs are a way to learn and dabble in opportunities to build in web3. These are neither full time jobs nor project based engagement. Please be advised that the companies will not have time for individualized feedback due to the number of entries we receive.</p>',
    requirements: null,
    deadline: null,
    eligibility: null,
    token: null,
    rewardAmount: null,
    rewards: null,
    color: "#F0F2FD",
    emoji: "📝",
    isFeatured: false,
    isActive: true,
    isArchived: false,
    createdAt: "2023-06-08T10:09:56.130Z",
    updatedAt: "2023-06-08T10:09:56.130Z",
    skills: [{ skills: "Content", subskills: ["Research"] }],
    type: "open",
    Jobs: [],
  },
  {
    id: "5",
    templateTitle: "Bug Job",
    templateDescription: null,
    title: "Bug Job",
    slug: "bug-job",
    description:
      "<h2>About Us</h2><p><em>A short paragraph (3-5 sentences) should be plenty here. Make sure to clearly communicate what the overall mission is, what unique value your project has, and any evidence of your traction. The goal should be to make your company feel like a rocket ship.</em></p><h2>&nbsp;</h2><h2>Bug Job Guidelines</h2><h3>Scope</h3><ul><li>What contracts, repos, etc are considered within scope?</li><li>What contracts, repos, etc are not within the scope of this bug job?</li></ul><h3>&nbsp;</h3><h3>Critical Risk</h3><ul><li>Description of what qualifies as Critical Risk (e.g. loss of funds)</li><li>Prize Amount</li></ul><h3>&nbsp;</h3><h3>High Level Risk:</h3><ul><li>Description of what qualifies as High Level Risk (e.g. users locked out of positions)</li><li>Prize Amount</li></ul><h3>&nbsp;</h3><h3>Mid Level Risk:</h3><ul><li>Description of what qualifies as Mid Level Risk</li><li>Prize Amount</li></ul><h3>&nbsp;</h3><h3>Low Level Risk:</h3><ul><li>Description of what qualifies as low risk (e.g. front-end issues, etc)</li><li>Prize Amount</li></ul><p>&nbsp;</p>",
    requirements: null,
    deadline: null,
    eligibility: null,
    token: null,
    rewardAmount: null,
    rewards: null,
    color: "#FBF0FD",
    emoji: "🐞",
    isFeatured: false,
    isActive: true,
    isArchived: false,
    createdAt: "2023-06-08T10:09:56.130Z",
    updatedAt: "2023-06-08T10:09:56.130Z",
    skills: [{ skills: "Blockchain", subskills: [] }],
    type: "open",
    Jobs: [],
  },
  {
    id: "6",
    templateTitle: "Freelance Designer",
    templateDescription: null,
    title: "Freelance Designer",
    slug: "freelance-designer",
    description:
      "<h2>Who We Are</h2><p><em>A short paragraph (3-5 sentences) should be plenty here. Make sure to clearly communicate what the overall mission is, along with any evidence of your traction. The goal should be to make your company feel like a rocket ship that applicants would be lucky to work with.</em></p><p>&nbsp;</p><h2>You&rsquo;ll Be Responsible for...</h2><p><em>Bullet point list of the scope of the role. What will they own? What kind of projects will they work on? More detail is better here to give applicants a clear sense of what they&rsquo;ll work on so they can envision their day-to-day.</em></p><p>&nbsp;</p><p>&nbsp;</p><h2>You&rsquo;re a Good Fit If...</h2><p><em>Include a bullet point list of requirements for the role (e.g. timezone, experience, tech stack, etc). Aim for ~5 requirements. More than that will turn off potential applicants</em></p><p>&nbsp;</p><p>&nbsp;</p><h2>You&rsquo;re a Perfect Fit if you have</h2><p><em>For &ldquo;optional&rdquo; or &ldquo;nice to have&rdquo; criteria, use this area. Again, try to limit ~5 or fewer requirements here.</em></p>",
    requirements: null,
    deadline: null,
    eligibility: null,
    token: null,
    rewardAmount: null,
    rewards: null,
    color: "#F0FDF5",
    emoji: "🥑",
    isFeatured: false,
    isActive: true,
    isArchived: false,
    createdAt: "2023-06-08T10:09:56.130Z",
    updatedAt: "2023-06-08T10:09:56.130Z",
    skills: [{ skills: "Design", subskills: [] }],
    type: "open",
    Jobs: [],
  },
  {
    id: "7",
    templateTitle: "Write a Twitter thread",
    templateDescription: null,
    title: "Write a Twitter thread",
    slug: "write-a-twitter-thread",
    description:
      "<h2>About the Job</h2><p><em>Below this box, please write ~2 paragraphs explaining the job. The first paragraph should include relevant context and background about your project. The second paragraph should explain what information needs to appear in the thread. </em></p><p>&nbsp;</p><p><strong>Your Mission</strong>: Become an expert on YOUR PROJECT NAME and summarize your findings in a Twitter thread with 8+ tweets.</p><h2>&nbsp;</h2><h2>Evaluation Criteria</h2><p><em>Job hunters will use the bullet points below to understand how they&rsquo;ll be evaluated. Feel free to add more criteria (e.g. if you want them to discuss a specific feature of your project), or edit the bullet points below as needed.</em></p><p>&nbsp;</p><h3>Depth</h3><ul><li>Did you explore the background of the project?</li><li>Does your thread talk about the key features of the project?</li><li>Is your thread the one-stop-resource for people to get up to speed with this project?</li><li>Did you learn everything there is to know about the project?</li><li>Did you try the competition and explain relative pros/cons of this project?</li></ul><p>&nbsp;</p><h3><strong>Writing Style</strong></h3><ul><li>Is your writing easy and fun to read?</li><li>Did you avoid overly complex jargon?</li><li>Did you explain concepts in a way a person new to crypto could understand?</li></ul><p>&nbsp;</p><h3><strong>Submission Requirements</strong></h3><ul><li>Did you tag the company in your Tweet thread, along with @SuperteamDAO?</li></ul><h2>&nbsp;</h2><h2>Resources</h2><p><em>Please add any links to your project, socials, or any reference essays that may help the job hunters write a great thread. Consider including your Medium/Substack, Twitter, Discord, docs, website, and anything else that might prove helpful.</em></p><h2>&nbsp;</h2><h2>Terms</h2><p>Participation in this job is entirely voluntary. Jobs are a way to learn and dabble in opportunities to build in web3. These are neither full time jobs nor project based engagement. Please be advised that the companies will not have time for individualized feedback due to the number of entries they receive.</p>",
    requirements: null,
    deadline: null,
    eligibility: null,
    token: null,
    rewardAmount: null,
    rewards: null,
    color: "#FDF0F0",
    emoji: "🧵",
    isFeatured: false,
    isActive: true,
    isArchived: false,
    createdAt: "2023-06-08T10:09:56.129Z",
    updatedAt: "2023-06-08T10:09:56.129Z",
    skills: [{ skills: "Content", subskills: ["Writing"] }],
    type: "open",
    Jobs: [],
  },
];
